name: museum_ticketing_app
description: A multilingual chatbot ticketing system for Tamil Nadu Museums with QR code and payment integration.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Official Flutter localization support
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  

  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9

  # Networking
  http: ^1.1.0
  dio: ^5.3.3
  retrofit: ^4.0.1

  # UI & Images
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  qr_flutter: ^4.0.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0

  # Payments
  razorpay_flutter: ^1.3.3

  # Localization
  easy_localization: ^3.0.2

  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  url_launcher: ^6.1.11
  intl_phone_number_input: ^0.7.3
  flutter_animate: ^4.1.1
  package_info_plus: ^4.0.2
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^6.0.0
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.3.1

flutter:
 
  uses-material-design: true
  generate: true
  assets:
    - assets/images/banner.jpg
    - assets/images/exhibition_chola.jpg
    - assets/images/exhibition_pallava.jpg
    - assets/images/highlight1.jpg
    - assets/images/highlight2.jpg
    - assets/images/highlight3.jpg
    - assets/images/login_background.jpg
    - assets/images/logo.png

