name: museum_ticketing_app
description: A multilingual chatbot ticketing system for Tamil Nadu Museums.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  razorpay_flutter: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/banner.jpg
    - assets/images/exhibition_chola.jpg
    - assets/images/exhibition_pallava.jpg
    - assets/images/highlight2.jpg
    - assets/images/highlight1.jpg
    - assets/images/highlight3.jpg
    #- assets/images/logo.svg
   # - assets/images/default_exhibition.jpg
